spring.application.name=TourBooking
server.port=8080

# Database
spring.data.mongodb.uri=mongodb://localhost:27017/tourweb

# JWT
jwt.signerKey=HkX2TSPYK2L92rjLzDLlwdABMD8x0VRBRhS8tLFeiEkJatfX1Sr4sDvlHTNOwdRO

# AWS
aws.accessKey=AKIAU6VTTPABKVAAUW5M
aws.secretKey=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
aws.region=ap-south-1
aws.bucketName=doanchungbucket

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Kafka
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
# Thi?t l?p deserializer cho consumer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.group-id=admin-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer


# Java Sender Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nvnthinh12a6@gmail.com 
spring.mail.password=qxxmpqowbhjldqwh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

payment.vnPay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
payment.vnPay.tmnCode=8KXZBIBM
payment.vnPay.secretKey=XW3GQ0O0MRM4EQ51K5RJO116WYJJ9NHQ
payment.vnPay.returnUrl=http://localhost:8080/payment/vn-pay-callback
payment.vnPay.version=2.1.0
payment.vnPay.command=pay
payment.vnPay.orderType=other

stripe.api.key=sk_test_51PIOKRP3o6slJaZ9NvicnYRGGabvUWOHfXidYb7HXvEG4nw8BsDNlE3aVIUMAH0B0safYGwgLx3ygsQMvFAjJCUD00J7ci7c92